#!/bin/bash
set -e

zig build

mkdir -p bin

if [ ! -e "./bin/boot.img" ]; then
	dd if=/dev/zero of=./bin/boot.img bs=512 count=93750
	sudo gdisk ./bin/boot.img <<EOF
o
y
n
1
2048
93716
ef00
w
y
EOF
	sudo losetup --offset 1048576 --sizelimit 46934528 /dev/loop0 ./bin/boot.img
	sudo mkfs.fat -F 32 /dev/loop0
	sudo losetup -d /dev/loop0
fi

sudo losetup --offset 1048576 --sizelimit 46934528 /dev/loop0 ./bin/boot.img
mkdir -p mnt
sudo mount /dev/loop0 ./mnt
sudo mkdir -p ./mnt/EFI/Boot
sudo cp ./zig-out/bin/BOOTx64.efi ./mnt/EFI/Boot/
sudo cp ./zig-out/bin/kernel.elf ./mnt
sudo umount ./mnt
rm -r ./mnt
sudo losetup -d /dev/loop0
